## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file 1.2.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_189 = Integer(189); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_264 = Integer(264); _sage_const_183 = Integer(183); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_24 = Integer(24); _sage_const_325 = Integer(325); _sage_const_18 = Integer(18); _sage_const_44 = Integer(44); _sage_const_89 = Integer(89); _sage_const_133 = Integer(133); _sage_const_111 = Integer(111); _sage_const_25 = Integer(25); _sage_const_231 = Integer(231); _sage_const_311 = Integer(311); _sage_const_257 = Integer(257); _sage_const_180 = Integer(180); _sage_const_271 = Integer(271); _sage_const_254 = Integer(254); _sage_const_198 = Integer(198); _sage_const_13 = Integer(13); _sage_const_38 = Integer(38); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_19 = Integer(19); _sage_const_32 = Integer(32); _sage_const_35 = Integer(35); _sage_const_12 = Integer(12); _sage_const_92 = Integer(92); _sage_const_95 = Integer(95); _sage_const_306 = Integer(306)## This file (1.2.sagetex.sage) was *autogenerated* from 1.2.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('1.2', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_16 
_st_.blockbegin()
try:
   latex.matrix_delimiters(left='[', right=']')
except:
 _st_.goboom(_sage_const_18 )
_st_.blockend()
_st_.current_tex_line = _sage_const_35 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_2 ,_sage_const_0 ],[_sage_const_4 ,_sage_const_1 ],[_sage_const_16 ,-_sage_const_3 /_sage_const_4 ]])
   B = matrix([[_sage_const_3 ,_sage_const_0 ,_sage_const_8 ,_sage_const_1 ,_sage_const_2 ],[_sage_const_7 ,-_sage_const_1 /_sage_const_2 ,_sage_const_3 ,_sage_const_2 ,_sage_const_10 ],[_sage_const_32 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ]])
except:
 _st_.goboom(_sage_const_38 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_44 
 _st_.inline(_sage_const_0 , latex(A))
except:
 _st_.goboom(_sage_const_44 )
try:
 _st_.current_tex_line = _sage_const_44 
 _st_.inline(_sage_const_1 , latex(B))
except:
 _st_.goboom(_sage_const_44 )
try:
 _st_.current_tex_line = _sage_const_44 
 _st_.inline(_sage_const_0 , latex(A))
except:
 _st_.goboom(_sage_const_44 )
try:
 _st_.current_tex_line = _sage_const_44 
 _st_.inline(_sage_const_1 , latex(B))
except:
 _st_.goboom(_sage_const_44 )
_st_.current_tex_line = _sage_const_89 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_3 ,_sage_const_1 ,_sage_const_8 ],[_sage_const_2 ,_sage_const_4 ,-_sage_const_1 ]])
   B = matrix([[_sage_const_0 ,-_sage_const_3 ,-_sage_const_4 ],[_sage_const_1 ,_sage_const_2 ,-_sage_const_7 ]])
except:
 _st_.goboom(_sage_const_92 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_95 
 _st_.inline(_sage_const_2 , latex(A))
except:
 _st_.goboom(_sage_const_95 )
try:
 _st_.current_tex_line = _sage_const_95 
 _st_.inline(_sage_const_3 , latex(B))
except:
 _st_.goboom(_sage_const_95 )
try:
 _st_.current_tex_line = _sage_const_95 
 _st_.inline(_sage_const_4 , latex(A+B))
except:
 _st_.goboom(_sage_const_95 )
try:
 _st_.current_tex_line = _sage_const_111 
 _st_.inline(_sage_const_5 , latex(A))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.current_tex_line = _sage_const_111 
 _st_.inline(_sage_const_6 , latex(_sage_const_6 *A))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.current_tex_line = _sage_const_133 
 _st_.inline(_sage_const_7 , latex(zero_matrix(_sage_const_3 ,_sage_const_4 )))
except:
 _st_.goboom(_sage_const_133 )
_st_.current_tex_line = _sage_const_180 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_3 ,_sage_const_4 ],[_sage_const_1 ,-_sage_const_8 ]])
   B = matrix([[_sage_const_1 ,_sage_const_0 ],[_sage_const_2 ,_sage_const_0 ],[_sage_const_3 ,_sage_const_1 ]])
except:
 _st_.goboom(_sage_const_183 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_189 
 _st_.inline(_sage_const_8 , latex(A))
except:
 _st_.goboom(_sage_const_189 )
try:
 _st_.current_tex_line = _sage_const_189 
 _st_.inline(_sage_const_9 , latex(B))
except:
 _st_.goboom(_sage_const_189 )
try:
 _st_.current_tex_line = _sage_const_189 
 _st_.inline(_sage_const_8 , latex(A))
except:
 _st_.goboom(_sage_const_189 )
try:
 _st_.current_tex_line = _sage_const_189 
 _st_.inline(_sage_const_9 , latex(B))
except:
 _st_.goboom(_sage_const_189 )
try:
 _st_.current_tex_line = _sage_const_198 
 _st_.inline(_sage_const_10 , latex(B))
except:
 _st_.goboom(_sage_const_198 )
try:
 _st_.current_tex_line = _sage_const_198 
 _st_.inline(_sage_const_11 , latex(A))
except:
 _st_.goboom(_sage_const_198 )
try:
 _st_.current_tex_line = _sage_const_198 
 _st_.inline(_sage_const_12 , latex(B*A))
except:
 _st_.goboom(_sage_const_198 )
try:
 _st_.current_tex_line = _sage_const_198 
 _st_.inline(_sage_const_10 , latex(B))
except:
 _st_.goboom(_sage_const_198 )
try:
 _st_.current_tex_line = _sage_const_198 
 _st_.inline(_sage_const_11 , latex(A))
except:
 _st_.goboom(_sage_const_198 )
try:
 _st_.current_tex_line = _sage_const_198 
 _st_.inline(_sage_const_12 , latex(B*A))
except:
 _st_.goboom(_sage_const_198 )
try:
 _st_.current_tex_line = _sage_const_231 
 _st_.inline(_sage_const_13 , latex(identity_matrix(_sage_const_2 )))
except:
 _st_.goboom(_sage_const_231 )
try:
 _st_.current_tex_line = _sage_const_231 
 _st_.inline(_sage_const_14 , latex(identity_matrix(_sage_const_3 )))
except:
 _st_.goboom(_sage_const_231 )
try:
 _st_.current_tex_line = _sage_const_231 
 _st_.inline(_sage_const_15 , latex(identity_matrix(_sage_const_4 )))
except:
 _st_.goboom(_sage_const_231 )
try:
 _st_.current_tex_line = _sage_const_231 
 _st_.inline(_sage_const_13 , latex(identity_matrix(_sage_const_2 )))
except:
 _st_.goboom(_sage_const_231 )
try:
 _st_.current_tex_line = _sage_const_231 
 _st_.inline(_sage_const_14 , latex(identity_matrix(_sage_const_3 )))
except:
 _st_.goboom(_sage_const_231 )
try:
 _st_.current_tex_line = _sage_const_231 
 _st_.inline(_sage_const_15 , latex(identity_matrix(_sage_const_4 )))
except:
 _st_.goboom(_sage_const_231 )
_st_.current_tex_line = _sage_const_254 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_0 ]])
   B = matrix([[_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ]])
except:
 _st_.goboom(_sage_const_257 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_264 
 _st_.inline(_sage_const_16 , latex(A))
except:
 _st_.goboom(_sage_const_264 )
try:
 _st_.current_tex_line = _sage_const_264 
 _st_.inline(_sage_const_17 , latex(B))
except:
 _st_.goboom(_sage_const_264 )
try:
 _st_.current_tex_line = _sage_const_264 
 _st_.inline(_sage_const_16 , latex(A))
except:
 _st_.goboom(_sage_const_264 )
try:
 _st_.current_tex_line = _sage_const_264 
 _st_.inline(_sage_const_17 , latex(B))
except:
 _st_.goboom(_sage_const_264 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_18 , latex(A))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_19 , latex(B))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_20 , latex(A*B))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_21 , latex(B))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_22 , latex(A))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_23 , latex(B*A))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_18 , latex(A))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_19 , latex(B))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_20 , latex(A*B))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_21 , latex(B))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_22 , latex(A))
except:
 _st_.goboom(_sage_const_271 )
try:
 _st_.current_tex_line = _sage_const_271 
 _st_.inline(_sage_const_23 , latex(B*A))
except:
 _st_.goboom(_sage_const_271 )
_st_.current_tex_line = _sage_const_306 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_2 ,-_sage_const_1 ,_sage_const_4 ],[_sage_const_1 ,-_sage_const_7 ,_sage_const_1 ],[-_sage_const_1 ,_sage_const_2 ,_sage_const_1 ]])
   var('x y z')
   vx = matrix([[x, y, z]]).transpose()
   b = matrix([[_sage_const_1 ,_sage_const_3 ,_sage_const_2 ]]).transpose()
except:
 _st_.goboom(_sage_const_311 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_325 
 _st_.inline(_sage_const_24 , latex(A))
except:
 _st_.goboom(_sage_const_325 )
try:
 _st_.current_tex_line = _sage_const_325 
 _st_.inline(_sage_const_25 , latex(vx))
except:
 _st_.goboom(_sage_const_325 )
try:
 _st_.current_tex_line = _sage_const_325 
 _st_.inline(_sage_const_26 , latex(b))
except:
 _st_.goboom(_sage_const_325 )
try:
 _st_.current_tex_line = _sage_const_325 
 _st_.inline(_sage_const_24 , latex(A))
except:
 _st_.goboom(_sage_const_325 )
try:
 _st_.current_tex_line = _sage_const_325 
 _st_.inline(_sage_const_25 , latex(vx))
except:
 _st_.goboom(_sage_const_325 )
try:
 _st_.current_tex_line = _sage_const_325 
 _st_.inline(_sage_const_26 , latex(b))
except:
 _st_.goboom(_sage_const_325 )
_st_.endofdoc()

