## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file 1.3.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_188 = Integer(188); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_182 = Integer(182); _sage_const_28 = Integer(28); _sage_const_29 = Integer(29); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_118 = Integer(118); _sage_const_44 = Integer(44); _sage_const_132 = Integer(132); _sage_const_48 = Integer(48); _sage_const_35 = Integer(35); _sage_const_187 = Integer(187); _sage_const_171 = Integer(171); _sage_const_156 = Integer(156); _sage_const_154 = Integer(154); _sage_const_151 = Integer(151); _sage_const_179 = Integer(179); _sage_const_33 = Integer(33); _sage_const_195 = Integer(195); _sage_const_32 = Integer(32); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_31 = Integer(31); _sage_const_30 = Integer(30); _sage_const_19 = Integer(19); _sage_const_18 = Integer(18); _sage_const_53 = Integer(53); _sage_const_51 = Integer(51); _sage_const_108 = Integer(108); _sage_const_98 = Integer(98); _sage_const_125 = Integer(125); _sage_const_93 = Integer(93); _sage_const_102 = Integer(102); _sage_const_107 = Integer(107); _sage_const_146 = Integer(146); _sage_const_143 = Integer(143); _sage_const_149 = Integer(149)## This file (1.3.sagetex.sage) was *autogenerated* from 1.3.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('1.3', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_16 
_st_.blockbegin()
try:
   latex.matrix_delimiters(left='[', right=']')
except:
 _st_.goboom(_sage_const_18 )
_st_.blockend()
_st_.current_tex_line = _sage_const_25 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_1 ,_sage_const_2 ],[_sage_const_3 ,_sage_const_5 ]])
   B = matrix([[-_sage_const_5 ,_sage_const_2 ],[_sage_const_3 ,-_sage_const_1 ]])
except:
 _st_.goboom(_sage_const_28 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_31 
 _st_.inline(_sage_const_0 , latex(A))
except:
 _st_.goboom(_sage_const_31 )
try:
 _st_.current_tex_line = _sage_const_31 
 _st_.inline(_sage_const_1 , latex(B))
except:
 _st_.goboom(_sage_const_31 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_2 , latex(A))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_3 , latex(B))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_4 , latex(A*B))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_5 , latex(B))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_6 , latex(A))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_7 , latex(B*A))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_2 , latex(A))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_3 , latex(B))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_4 , latex(A*B))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_5 , latex(B))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_6 , latex(A))
except:
 _st_.goboom(_sage_const_35 )
try:
 _st_.current_tex_line = _sage_const_35 
 _st_.inline(_sage_const_7 , latex(B*A))
except:
 _st_.goboom(_sage_const_35 )
_st_.current_tex_line = _sage_const_44 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_1 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_0 ]])
   var('b11 b12 b21 b22')
   B = matrix([[b11, b12],[b21, b22]])
except:
 _st_.goboom(_sage_const_48 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_51 
 _st_.inline(_sage_const_8 , latex(A))
except:
 _st_.goboom(_sage_const_51 )
try:
 _st_.current_tex_line = _sage_const_53 
 _st_.inline(_sage_const_9 , latex(A))
except:
 _st_.goboom(_sage_const_53 )
try:
 _st_.current_tex_line = _sage_const_53 
 _st_.inline(_sage_const_10 , latex(B))
except:
 _st_.goboom(_sage_const_53 )
try:
 _st_.current_tex_line = _sage_const_53 
 _st_.inline(_sage_const_11 , latex(A*B))
except:
 _st_.goboom(_sage_const_53 )
_st_.current_tex_line = _sage_const_93 
_st_.blockbegin()
try:
   import gaussjordan
   A = matrix([[_sage_const_2 ,_sage_const_1 ,_sage_const_3 ],[_sage_const_2 ,_sage_const_1 ,_sage_const_1 ],[_sage_const_4 ,_sage_const_5 ,_sage_const_1 ]])
   B = identity_matrix(_sage_const_3 )
   M = A.augment(B, subdivide=True)
except:
 _st_.goboom(_sage_const_98 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_102 
 _st_.inline(_sage_const_12 , latex(A))
except:
 _st_.goboom(_sage_const_102 )
try:
 _st_.current_tex_line = _sage_const_107 
 _st_.inline(_sage_const_13 , latex(gaussjordan.latex_reduction(M)))
except:
 _st_.goboom(_sage_const_107 )
try:
 _st_.current_tex_line = _sage_const_108 
 _st_.inline(_sage_const_14 , latex(A.inverse()))
except:
 _st_.goboom(_sage_const_108 )
_st_.current_tex_line = _sage_const_118 
_st_.blockbegin()
try:
   I2 = identity_matrix(_sage_const_2 )
   E2 = elementary_matrix(_sage_const_2 , row1=_sage_const_1 , scale=_sage_const_3 )
   I3 = identity_matrix(_sage_const_3 )
   E3 = elementary_matrix(_sage_const_3 , row1=_sage_const_1 , row2=_sage_const_0 , scale=-_sage_const_1 /_sage_const_2 )
   I4 = identity_matrix(_sage_const_4 )
   E4 = elementary_matrix(_sage_const_4 , row1=_sage_const_2 , row2=_sage_const_3 )
except:
 _st_.goboom(_sage_const_125 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_15 , latex(I2))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_16 , latex(E2))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_17 , latex(I3))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_18 , latex(E3))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_19 , latex(I4))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_20 , latex(E4))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_15 , latex(I2))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_16 , latex(E2))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_17 , latex(I3))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_18 , latex(E3))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_19 , latex(I4))
except:
 _st_.goboom(_sage_const_132 )
try:
 _st_.current_tex_line = _sage_const_132 
 _st_.inline(_sage_const_20 , latex(E4))
except:
 _st_.goboom(_sage_const_132 )
_st_.current_tex_line = _sage_const_143 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_1 ,_sage_const_7 ],[_sage_const_0 ,_sage_const_1 /_sage_const_3 ]])
   E = elementary_matrix(_sage_const_2 , row1=_sage_const_1 , scale=_sage_const_3 )
except:
 _st_.goboom(_sage_const_146 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_149 
 _st_.inline(_sage_const_21 , latex(A))
except:
 _st_.goboom(_sage_const_149 )
try:
 _st_.current_tex_line = _sage_const_151 
 _st_.inline(_sage_const_22 , latex(A))
except:
 _st_.goboom(_sage_const_151 )
try:
 _st_.current_tex_line = _sage_const_151 
 _st_.inline(_sage_const_23 , latex(E*A))
except:
 _st_.goboom(_sage_const_151 )
try:
 _st_.current_tex_line = _sage_const_154 
 _st_.inline(_sage_const_24 , latex(E))
except:
 _st_.goboom(_sage_const_154 )
try:
 _st_.current_tex_line = _sage_const_156 
 _st_.inline(_sage_const_25 , latex(E))
except:
 _st_.goboom(_sage_const_156 )
try:
 _st_.current_tex_line = _sage_const_156 
 _st_.inline(_sage_const_26 , latex(A))
except:
 _st_.goboom(_sage_const_156 )
try:
 _st_.current_tex_line = _sage_const_156 
 _st_.inline(_sage_const_27 , latex(E*A))
except:
 _st_.goboom(_sage_const_156 )
_st_.current_tex_line = _sage_const_171 
_st_.blockbegin()
try:
   import gaussjordan
   A = matrix([[_sage_const_1 ,_sage_const_2 ],[_sage_const_3 ,_sage_const_5 ]])
   B = identity_matrix(_sage_const_2 )
   M = A.augment(B, subdivide=True)
   E1 = elementary_matrix(_sage_const_2 , row1=_sage_const_1 , row2=_sage_const_0 , scale=-_sage_const_3 )
   E2 = elementary_matrix(_sage_const_2 , row1=_sage_const_1 , scale=-_sage_const_1 )
   E3 = elementary_matrix(_sage_const_2 , row1=_sage_const_0 , row2=_sage_const_1 , scale=-_sage_const_2 )
except:
 _st_.goboom(_sage_const_179 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_182 
 _st_.inline(_sage_const_28 , latex(A))
except:
 _st_.goboom(_sage_const_182 )
try:
 _st_.current_tex_line = _sage_const_187 
 _st_.inline(_sage_const_29 , latex(gaussjordan.latex_reduction(M)))
except:
 _st_.goboom(_sage_const_187 )
try:
 _st_.current_tex_line = _sage_const_188 
 _st_.inline(_sage_const_30 , latex(A.inverse()))
except:
 _st_.goboom(_sage_const_188 )
try:
 _st_.current_tex_line = _sage_const_195 
 _st_.inline(_sage_const_31 , latex(E1))
except:
 _st_.goboom(_sage_const_195 )
try:
 _st_.current_tex_line = _sage_const_195 
 _st_.inline(_sage_const_32 , latex(E2))
except:
 _st_.goboom(_sage_const_195 )
try:
 _st_.current_tex_line = _sage_const_195 
 _st_.inline(_sage_const_33 , latex(E3))
except:
 _st_.goboom(_sage_const_195 )
try:
 _st_.current_tex_line = _sage_const_195 
 _st_.inline(_sage_const_31 , latex(E1))
except:
 _st_.goboom(_sage_const_195 )
try:
 _st_.current_tex_line = _sage_const_195 
 _st_.inline(_sage_const_32 , latex(E2))
except:
 _st_.goboom(_sage_const_195 )
try:
 _st_.current_tex_line = _sage_const_195 
 _st_.inline(_sage_const_33 , latex(E3))
except:
 _st_.goboom(_sage_const_195 )
_st_.endofdoc()

