## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file 1.4.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_27 = Integer(27); _sage_const_24 = Integer(24); _sage_const_134 = Integer(134); _sage_const_131 = Integer(131); _sage_const_68 = Integer(68); _sage_const_16 = Integer(16); _sage_const_33 = Integer(33); _sage_const_18 = Integer(18); _sage_const_77 = Integer(77); _sage_const_98 = Integer(98); _sage_const_71 = Integer(71); _sage_const_100 = Integer(100); _sage_const_96 = Integer(96); _sage_const_140 = Integer(140)## This file (1.4.sagetex.sage) was *autogenerated* from 1.4.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('1.4', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_16 
_st_.blockbegin()
try:
   latex.matrix_delimiters(left='[', right=']')
except:
 _st_.goboom(_sage_const_18 )
_st_.blockend()
_st_.current_tex_line = _sage_const_24 
_st_.blockbegin()
try:
   A = matrix.diagonal([_sage_const_3 ,-_sage_const_1 ,_sage_const_1 /_sage_const_2 ,_sage_const_0 ])
   B = matrix.diagonal([_sage_const_3 ,_sage_const_1 ])
except:
 _st_.goboom(_sage_const_27 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_33 
 _st_.inline(_sage_const_0 , latex(A))
except:
 _st_.goboom(_sage_const_33 )
try:
 _st_.current_tex_line = _sage_const_33 
 _st_.inline(_sage_const_1 , latex(B))
except:
 _st_.goboom(_sage_const_33 )
try:
 _st_.current_tex_line = _sage_const_33 
 _st_.inline(_sage_const_0 , latex(A))
except:
 _st_.goboom(_sage_const_33 )
try:
 _st_.current_tex_line = _sage_const_33 
 _st_.inline(_sage_const_1 , latex(B))
except:
 _st_.goboom(_sage_const_33 )
_st_.current_tex_line = _sage_const_68 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_1 ,_sage_const_4 ,_sage_const_2 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_4 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ]])
   B = matrix([[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_2 ,_sage_const_8 ,_sage_const_0 ],[_sage_const_4 ,_sage_const_9 ,_sage_const_7 ]])
except:
 _st_.goboom(_sage_const_71 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_77 
 _st_.inline(_sage_const_2 , latex(A))
except:
 _st_.goboom(_sage_const_77 )
try:
 _st_.current_tex_line = _sage_const_77 
 _st_.inline(_sage_const_3 , latex(B))
except:
 _st_.goboom(_sage_const_77 )
try:
 _st_.current_tex_line = _sage_const_77 
 _st_.inline(_sage_const_2 , latex(A))
except:
 _st_.goboom(_sage_const_77 )
try:
 _st_.current_tex_line = _sage_const_77 
 _st_.inline(_sage_const_3 , latex(B))
except:
 _st_.goboom(_sage_const_77 )
_st_.current_tex_line = _sage_const_96 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_1 ,_sage_const_2 ,_sage_const_3 ],[_sage_const_4 ,_sage_const_5 ,_sage_const_6 ]])
except:
 _st_.goboom(_sage_const_98 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_4 , latex(A))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_5 , latex(A.transpose()))
except:
 _st_.goboom(_sage_const_100 )
_st_.current_tex_line = _sage_const_131 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_1 ,_sage_const_2 ,_sage_const_3 ],[_sage_const_2 ,_sage_const_4 ,_sage_const_5 ],[_sage_const_3 ,_sage_const_5 ,_sage_const_6 ]])
   B = matrix([[_sage_const_1 ,_sage_const_2 ,_sage_const_3 ],[_sage_const_4 ,_sage_const_5 ,_sage_const_6 ],[_sage_const_7 ,_sage_const_8 ,_sage_const_9 ]])
except:
 _st_.goboom(_sage_const_134 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_140 
 _st_.inline(_sage_const_6 , latex(A))
except:
 _st_.goboom(_sage_const_140 )
try:
 _st_.current_tex_line = _sage_const_140 
 _st_.inline(_sage_const_7 , latex(B))
except:
 _st_.goboom(_sage_const_140 )
try:
 _st_.current_tex_line = _sage_const_140 
 _st_.inline(_sage_const_6 , latex(A))
except:
 _st_.goboom(_sage_const_140 )
try:
 _st_.current_tex_line = _sage_const_140 
 _st_.inline(_sage_const_7 , latex(B))
except:
 _st_.goboom(_sage_const_140 )
_st_.endofdoc()

