## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file 1.6.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_28 = Integer(28); _sage_const_183 = Integer(183); _sage_const_30 = Integer(30); _sage_const_22 = Integer(22); _sage_const_23 = Integer(23); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_26 = Integer(26); _sage_const_19 = Integer(19); _sage_const_24 = Integer(24); _sage_const_25 = Integer(25); _sage_const_18 = Integer(18); _sage_const_62 = Integer(62); _sage_const_111 = Integer(111); _sage_const_27 = Integer(27); _sage_const_171 = Integer(171); _sage_const_173 = Integer(173); _sage_const_37 = Integer(37); _sage_const_179 = Integer(179); _sage_const_159 = Integer(159); _sage_const_29 = Integer(29); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_17 = Integer(17); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_31 = Integer(31); _sage_const_131 = Integer(131); _sage_const_55 = Integer(55); _sage_const_32 = Integer(32); _sage_const_35 = Integer(35); _sage_const_51 = Integer(51); _sage_const_109 = Integer(109); _sage_const_120 = Integer(120); _sage_const_164 = Integer(164); _sage_const_129 = Integer(129); _sage_const_106 = Integer(106); _sage_const_145 = Integer(145); _sage_const_147 = Integer(147); _sage_const_143 = Integer(143)## This file (1.6.sagetex.sage) was *autogenerated* from 1.6.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('1.6', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_16 
_st_.blockbegin()
try:
   latex.matrix_delimiters(left='[', right=']')
except:
 _st_.goboom(_sage_const_18 )
_st_.blockend()
_st_.current_tex_line = _sage_const_32 
_st_.blockbegin()
try:
   A = matrix([[_sage_const_1 ,_sage_const_3 ,_sage_const_4 ],[_sage_const_2 ,_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_2 ]])
   A12 = A.delete_rows([_sage_const_0 ]).delete_columns([_sage_const_1 ])
except:
 _st_.goboom(_sage_const_35 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_37 
 _st_.inline(_sage_const_0 , latex(A))
except:
 _st_.goboom(_sage_const_37 )
try:
 _st_.current_tex_line = _sage_const_37 
 _st_.inline(_sage_const_1 , latex(A12))
except:
 _st_.goboom(_sage_const_37 )
try:
 _st_.current_tex_line = _sage_const_37 
 _st_.inline(_sage_const_2 , latex(A))
except:
 _st_.goboom(_sage_const_37 )
_st_.current_tex_line = _sage_const_51 
_st_.blockbegin()
try:
   E1 = elementary_matrix(_sage_const_3 , row1=_sage_const_1 , row2=_sage_const_2 )
   E2 = elementary_matrix(_sage_const_3 , row1=_sage_const_1 , scale=-_sage_const_3 )
   E3 = elementary_matrix(_sage_const_3 , row1=_sage_const_0 , row2=_sage_const_1 , scale=_sage_const_2 )
except:
 _st_.goboom(_sage_const_55 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_3 , latex(E1))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_4 , latex(E1.det()))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_5 , latex(E2))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_6 , latex(E2.det()))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_7 , latex(E3))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_8 , latex(E3.det()))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_3 , latex(E1))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_4 , latex(E1.det()))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_5 , latex(E2))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_6 , latex(E2.det()))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_7 , latex(E3))
except:
 _st_.goboom(_sage_const_62 )
try:
 _st_.current_tex_line = _sage_const_62 
 _st_.inline(_sage_const_8 , latex(E3.det()))
except:
 _st_.goboom(_sage_const_62 )
_st_.current_tex_line = _sage_const_106 
_st_.blockbegin()
try:
   var('a b c d')
   A = matrix([[a,b],[c,d]])
except:
 _st_.goboom(_sage_const_109 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_111 
 _st_.inline(_sage_const_9 , latex(A))
except:
 _st_.goboom(_sage_const_111 )
try:
 _st_.current_tex_line = _sage_const_120 
 _st_.inline(_sage_const_10 , latex(A.adjoint().transpose()))
except:
 _st_.goboom(_sage_const_120 )
try:
 _st_.current_tex_line = _sage_const_120 
 _st_.inline(_sage_const_11 , latex(A.adjoint()))
except:
 _st_.goboom(_sage_const_120 )
try:
 _st_.current_tex_line = _sage_const_120 
 _st_.inline(_sage_const_10 , latex(A.adjoint().transpose()))
except:
 _st_.goboom(_sage_const_120 )
try:
 _st_.current_tex_line = _sage_const_120 
 _st_.inline(_sage_const_11 , latex(A.adjoint()))
except:
 _st_.goboom(_sage_const_120 )
try:
 _st_.current_tex_line = _sage_const_129 
 _st_.inline(_sage_const_12 , latex(A))
except:
 _st_.goboom(_sage_const_129 )
try:
 _st_.current_tex_line = _sage_const_129 
 _st_.inline(_sage_const_13 , latex(A.adjoint()))
except:
 _st_.goboom(_sage_const_129 )
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_14 , latex(A))
except:
 _st_.goboom(_sage_const_131 )
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_15 , latex(A.adjoint()))
except:
 _st_.goboom(_sage_const_131 )
try:
 _st_.current_tex_line = _sage_const_131 
 _st_.inline(_sage_const_16 , latex(A*A.adjoint()))
except:
 _st_.goboom(_sage_const_131 )
try:
 _st_.current_tex_line = _sage_const_143 
 _st_.inline(_sage_const_17 , latex(A))
except:
 _st_.goboom(_sage_const_143 )
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_18 , latex(A.det()))
except:
 _st_.goboom(_sage_const_145 )
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_19 , latex(A.adjoint()))
except:
 _st_.goboom(_sage_const_145 )
try:
 _st_.current_tex_line = _sage_const_147 
 _st_.inline(_sage_const_20 , latex(A.det()))
except:
 _st_.goboom(_sage_const_147 )
_st_.current_tex_line = _sage_const_159 
_st_.blockbegin()
try:
   var('a b c d x1 x2 b1 b2')
   A = matrix([[a, b],[c, d]])
   x = matrix.column([x1, x2])
   b = matrix.column([b1, b2])
except:
 _st_.goboom(_sage_const_164 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_171 
 _st_.inline(_sage_const_21 , latex(A))
except:
 _st_.goboom(_sage_const_171 )
try:
 _st_.current_tex_line = _sage_const_171 
 _st_.inline(_sage_const_22 , latex(x))
except:
 _st_.goboom(_sage_const_171 )
try:
 _st_.current_tex_line = _sage_const_171 
 _st_.inline(_sage_const_23 , latex(b))
except:
 _st_.goboom(_sage_const_171 )
try:
 _st_.current_tex_line = _sage_const_171 
 _st_.inline(_sage_const_21 , latex(A))
except:
 _st_.goboom(_sage_const_171 )
try:
 _st_.current_tex_line = _sage_const_171 
 _st_.inline(_sage_const_22 , latex(x))
except:
 _st_.goboom(_sage_const_171 )
try:
 _st_.current_tex_line = _sage_const_171 
 _st_.inline(_sage_const_23 , latex(b))
except:
 _st_.goboom(_sage_const_171 )
_st_.current_tex_line = _sage_const_173 
_st_.blockbegin()
try:
     latex.matrix_delimiters(left='|', right='|')
     var('a b c d x1 x2 b1 b2')
     A1 = matrix([[b1, b],[b2, d]])
     A2 = matrix([[a, b1],[c, b2]])
     A = matrix([[a, b],[c, d]])
   
except:
 _st_.goboom(_sage_const_179 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_24 , latex(A1))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_25 , latex(A))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_26 , latex(A1.det()))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_27 , latex(A.det()))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_28 , latex(A2))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_29 , latex(A))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_30 , latex(A2.det()))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_31 , latex(A.det()))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_24 , latex(A1))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_25 , latex(A))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_26 , latex(A1.det()))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_27 , latex(A.det()))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_28 , latex(A2))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_29 , latex(A))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_30 , latex(A2.det()))
except:
 _st_.goboom(_sage_const_183 )
try:
 _st_.current_tex_line = _sage_const_183 
 _st_.inline(_sage_const_31 , latex(A.det()))
except:
 _st_.goboom(_sage_const_183 )
_st_.endofdoc()

